Started adding options. Not currently working.
davleop/godu pull request #2
Opened 2022-06-29 04:11 UTC by prescient-slime

Can't get Cobra to respect flags that I'm adding to the root command. I'll figure it out tomorrow. I like Cobra's structure I just feel like I'm doing something stupid.

2022-06-29 13:17 UTC, davleop commented on main.go
> +				fmt.Println("it brokey")
If something breaks the program, we should probably use `log.Fatal` or something in the `log` lib

2022-06-29 13:46 UTC, davleop commented
I'll probably change the base branch to merge into to be the `development` branch rather than `main`. So `main` will be our mvp

2022-07-02 15:38 UTC, davleop commented on main.go
> +	//commented out to avoid going into tui every time I tested code.
We can probably delete the comments for this merge. I'll have something new to replace the Bubble Tea stuff in the next PR I make

2022-07-02 15:39 UTC, davleop requested changes
See comment made for main.go.

2022-07-02 15:56 UTC, davleop commented
#3 Got merged. Do we need to keep this PR?

2022-07-05 14:47 UTC, prescient-slime commented
> #3 Got merged. Do we need to keep this PR?

No we don't. It's fine to close.

2022-07-05 14:53 UTC, closed without merging